---
output:
  html_document:
    css: www/styles.css
    anchor_sections: FALSE
    includes:
      in_header: "header_manual.html"

params:
  year_curr: 2024 # Current year of sampling
  park: "ACAD"
  all_years: TRUE # If FALSE, only reports on year_curr; TRUE reports on all years
  
---
```{r setup, include = F}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = '', scipen = 100)
```

```{r imports, include = FALSE}
library(rockyIntertidal)
library(tidyverse)
library(knitr)
library(kableExtra)
library(htmltools) # for tagList

importData()
park = params$park
year_curr = params$year_curr
year = 2013:year_curr

# year = 2013:2024
# park = "ACAD"
# year_curr = 2024
# 
arglist <- list(park = park, years = year)

locs <- do.call(getPIBoltDistance, arglist) |>
  select(SiteCode) |> unique() |> c() #|> as.character()
```

Rocky intertidal Quality Control checking for `r params$park` and `r paste(year, collapse = ", ")` {.tabset .tabset-pills}
---

```{r, include = F, results = 'hide'}
source('park_QC_checks_compile.R')
```

```{r, warning = FALSE, message = FALSE, results = 'hide', include = FALSE, eval = F}
#---- Plotting bolt elevation by distance -----
trans_contour_plots <- 
  purrr::map(locs$SiteCode, 
             ~plotPITransects(
               site = ., xlab = "Distance (m)", ylab = "Elevation MLLW (m)", 
               title = TRUE, years = 2013:year_curr)) |> set_names(locs$SiteCode)

#---- Plotting species by elevation -----
trans_species_plots <- 
  purrr::map(locs$SiteCode,
             ~plotPISpecies(site = ., xlab = "Year", ylab = "Elevation MLLW (m)", 
                                    title = TRUE, years = 2013:year_curr, facet = T) +
    theme(legend.position = 'bottom',
          legend.text = element_text(size = 10),
          legend.key.size = unit(0.5, 'cm'),
          legend.key.width = unit(0.5, 'cm'),
          legend.key.height = unit(0.5, 'cm'),
          legend.title = element_blank())) |> set_names(locs$SiteCode)

#---- Plotting photoplot cover by target species and site ----
photo_species_plots <- purrr::map(locs$SiteCode,
  ~plotPhotoCover(site = ., top_spp = 3, years = 2013:year_curr, plotly = T)                                
  ) |> set_names(locs$SiteCode)


#---- Plotting motile invert counts by target species and site ----
motinv_species_plots <- purrr::map(locs$SiteCode,
  ~plotMotileInvertCounts(site = ., main_groups = TRUE, years = 2013:year_curr, 
                          plotly = T)) |> set_names(locs$SiteCode)

#---- Plotting motile invert measures by target species and site ----
motinv_meas_plots <- purrr::map(locs$SiteCode,
  ~plotMotileInvertMeas(site = ., years = 2013:year_curr)) |> 
  set_names(locs$SiteCode)

#---- Plotting echinorderm counts by site
echino_cnt_plots <- purrr::map(locs$SiteCode,
  ~plotEchinoCounts(site = ., years = 2013:year_curr, plotly = T)) |> set_names(locs$SiteCode)

echino_meas_plots <- purrr::map(locs$SiteCode,
  ~plotEchinoMeas(site = ., years = 2013:year_curr)) |> set_names(locs$SiteCode)

```

### QC Checks {.tabset}

<hr>

#### Summary {.tabset}
```{r}
QC_check_table
```

```{r echo = F, eval = include_visit_table, results = 'asis'}
cat("#### Compiled Notes", "\n")
if(include_visit_table == TRUE){
  visit_table
}
```

```{r eval = pit_include, results = 'asis'}
cat("### Point Intercept Transects {.tabset} ", "\n\n")

cat("<hr>")

check_null_print(miss_bolt_elev_dist, 4, "Missing distance")
  
check_null_print(later_bolt_dist_0, 4, "0 after first bolt")

check_null_print(nonchron_bolt_dist, 4, "Bolts out of order")

check_null_print(missing_bolts, 4, "Missed bolts")

check_null_print(short_trans, 4, "Short transects")

check_null_print(long_trans, 4, "Long transects")

check_null_print(missing_trans, 4, "Missed transects")

check_null_print(bolt_check_tbl, 4, "Impossible elev. X dist.")

check_null_print(spp_high_elev, 4, "Spp. elev. above hist. range")

check_null_print(spp_low_elev, 4, "Spp. elev. below hist. range")
```


```{r include = F, results = 'hide'}
# Nesting substrate and motile inverts within photoplots
photoplot_eval <- ifelse(photoplot_include == TRUE | photoplot_mi_include == TRUE, TRUE, FALSE)
```

```{r eval = photoplot_include, results = 'asis'}
cat("### Photoplot Cover {.tabset} ", "\n\n")

cat("<hr>")

check_null_print(photo_sch_tbl, 4, "Plot not sampled")

check_null_print(miss_photo_bolts, 4, "Photoplots missing bolts")

check_null_print(photoplot_tbl, 4, "Duplicate scoring")

check_null_print(photoplot2_tbl, 4, "Years missing scores")

check_null_print(covsum_tbl, 4, "Total cover under 100")

check_null_print(pctcov_sum_tbl, 4, "Total cover over 100")

check_null_print(covsum0_tbl, 4, "Total cover sums to 0")


#check_null_print(spp_plot_tbl, 4, "Missing or dup. species cover") # hard to make sense of this one; 
# replacing with schedule of sites and plots with records

```

```{r eval = photoplot_mi_include, results = 'asis'}
cat("### Motile Inverts {.tabset} ", "\n\n")

check_null_print(micnt_nas_tbl, 4, "Counts with NAs")

check_null_print(micnt_99dam_tbl, 4, "Damage counts over 99pct")

check_null_print(micnt_99nodam_tbl, 4, "No.Damage counts over 99pct")

check_null_print(mimeas_nas_tbl, 4, "Meas. with NAs")

check_null_print(mimeas_99.9_tbl, 4, "Meas. over 99.9cm")

check_null_print(mimeas_99_tbl, 4, "Meas. over 99pct")

check_null_print(mimeas_0_tbl, 4, "Meas. of 0")

check_null_print(mimeas11_tbl, 4, "Meas. counts over 10")

check_null_print(mi_crab_tbl, 4, "Crabs with meas.")

check_null_print(mi_meas_miss_tbl, 4, "Fewer meas. than counts")

check_null_print(mi_cnt_miss_tbl, 4, "Fewer counts than meas.")

```

### Echinoderms {.tabset}
```{r eval = echino_include, results = 'asis'}
cat("#### QC Checks {.tabset}", "\n\n")
cat("<details open><summary class = 'drop'>", "<h3>Echinoderm Counts</h3>", "</summary>")
check_null(eccnt_nas_tbl)

check_null(eccnt_99_tbl)

cat("<details open><summary class = 'drop'>", "<h3>Echinoderm Measurements</h3>", "</summary>")
check_null(ecmeas_nas_tbl)

check_null(ecmeas_99.9_tbl)

check_null(ecmeas_99_tbl)

check_null(ecmeas_0_tbl)

cat("</details>")

```


### Recruitment Plots

No checks added yet



